### ISSUE TITLE
live CC

### ISSUE THREAD

**Issue by pkviet** [szatmary/libcaption#17]
hello,
I checked your example script. Would this work for a live stream with a text file updated regularly ?
A suggestion: in OBS studio  enable the ingestion of a live text file (maybe the code you committed already allows that)
This is of interest with fast transcribers (steno) during live streaming.

**Comment by szatmary** [comment]
flv+srt can read from a named pipe, and will make timestamps relative to the flv timestamps.
So, if you were to `mkfifo /run/srt` then pipe the flv through `fly+srt` and write captions to the named pipe in srt format, with a time stamp of zero and a null terminator it would work.

Although I don't believe that would be the best way to achieve what you want. Personally, I think adding the functionality directly to OBS would be better. OBS could feed libcaption the typed text, instead of the recognized text, and the rest is already in place.

**Comment by pkviet** [comment]
ok thanks a lot. Any plans to add libcaption to ffmpeg ? I'd also like to be able to add captions to a live mpeg-ts stream.

**Comment by szatmary** [comment]
Unfortunately, I do not have the time to do that, but I would be happy to support somebody else effort.

**Comment by widgeteye** [comment]
can this be used to extract cc from a recorded ota television program file? If so how?

thanks

**Comment by szatmary** [comment]
It could be used for that, yes. You just need to write a program to pull the user_data from the elementary stream and use this library to parse it.
